core/core-impl/src/main/java/org/openbaton/nfvo/core/core/ResourceManagement.java
One redundant statement removed and other one corrected
=> corrections in config defaults

api/src/main/java/org/openbaton/nfvo/api/RestVirtualLink.java
=> Remove redundant /

api/src/main/java/org/openbaton/nfvo/api/RestUsers.java, security/src/main/java/org/openbaton/nfvo/security/authorization/UserManagement.java, security/src/main/java/org/openbaton/nfvo/security/interfaces/UserManagement.java
=> Fix: Fix issue of deleting admin user

api/src/main/java/org/openbaton/nfvo/api/interceptors/AuthorizeInterceptor.java, security/src/main/java/org/openbaton/nfvo/security/authentication/CustomUserDetailsService.java, security/src/main/java/org/openbaton/nfvo/security/authorization/ProjectManagement.java, security/src/main/java/org/openbaton/nfvo/security/interfaces/ProjectManagement.java
Fix 
* delete of project without project-id header
* creation of "default" project when not needed
* not possible to remove last project
resolves #28
=> Fix Issue #28

api/src/main/java/org/openbaton/nfvo/api/RestVimInstances.java
hiding admin password while returning VIM object via REST APIs
=> fea: hiding password from REST APIs for GET VIM(s)

api/src/main/java/org/openbaton/nfvo/api/admin/RestUsers.java, security/src/main/java/org/openbaton/nfvo/security/authorization/UserManagement.java, security/src/main/java/org/openbaton/nfvo/security/interfaces/UserManagement.java
Admins can change passwords of other users
=> Fix: this fixes partially issue #55 - see comments

etc/openbaton.properties, gradle/gradle/scripts/debian/postinst
Add the support for the configuration file during the bootstrap.
Clean the properties file.
Update configurations after the clean properties file.
Add the upgrade of the properties file.
=> Config file

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VNFPackageManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/core/VnfPlacementManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/NetworkServiceRecordManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/VnfPlacementManagement.java
ignore the scaleOut method. It is not used at this point and don't causes issues.
=> Fix vims selection if no VIMs are defined in VNFD

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/core/VNFLifecycleOperationGranting.java, core/core-impl/src/test/java/org/openbaton/nfvo/core/test/VNFLifecycleOperationGrantingClassSuiteTest.java, main/src/main/resources/application.properties
Add option to skip quota check -> nfvo.quota.check=true (default)
Add option to fail or proceed after exception thrown while checking quotas -> nfvo.quota.check.failOnException=true (default)
=> Fix: quota check while deploying

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java
Fixing the issue where the configuration parameters where not updated but added only
=> Fix: add/update of configuration parameters when deploying

core/core-impl/src/main/java/org/openbaton/nfvo/core/core/ResourceManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/ResourceManagement.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/AllocateresourcesTask.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/ScalingTask.java
=> Fix: issue #89 Allocate Resource Bug

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java
=> Fix: failing scaling operation in case of multiple VDUs

core/core-impl/src/main/java/org/openbaton/nfvo/core/core/ResourceManagement.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/AllocateresourcesTask.java
=> VDU deployment in parallel

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceDescriptorManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, main/src/main/java/org/openbaton/nfvo/system/FlywayConfig.java, main/src/main/resources/flyway/V3_2_0_1__Add_createdAt_updatedAt_to_NSD_VNFD_NSR_NSD.sql, main/src/main/resources/flyway/V3_2_0_2__Add_nfvo_version_to_NSD_VNFD.sql, openbaton-libs/catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/NetworkServiceDescriptor.java, openbaton-libs/catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/VirtualNetworkFunctionDescriptor.java, openbaton-libs/catalogue/src/main/java/org/openbaton/catalogue/mano/record/NetworkServiceRecord.java, openbaton-libs/catalogue/src/main/java/org/openbaton/catalogue/mano/record/VirtualNetworkFunctionRecord.java, repository/src/main/java/org/openbaton/nfvo/repositories/NetworkServiceDescriptorRepositoryImpl.java, repository/src/main/java/org/openbaton/nfvo/repositories/NetworkServiceRecordRepositoryImpl.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/VnfmManager.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/abstracts/AbstractTask.java
Handle createdAt/updatedAt to NSD, VNFD, NSR, VNFR (covers issue #97)
Add nfvo_version to NSD and VNFD
=> Add params

tosca-parser/src/main/java/org/openbaton/tosca/parser/CSARParser.java, tosca-parser/src/main/java/org/openbaton/tosca/parser/TOSCAParser.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/NSDTemplate.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/CP/CPProperties.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VDU/VDUNodeTemplate.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VDU/VDUProperties.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VNF/VNFProperties.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/TopologyTemplate.java, tosca-parser/src/main/resources/Testing/testTopologyTemplate.yaml, tosca-parser/src/main/resources/Testing/testVNFDTemplate.yaml
Unused parameters where deleted and the interfaceId was introduced
=> Parser refactoring and interfaceId introduction

api/src/main/java/org/openbaton/nfvo/api/catalogue/RestNetworkServiceDescriptor.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceDescriptorManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/NetworkServiceDescriptorManagement.java
=> Fix: issue #112 - updating NSD

core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/NSDUtils.java
=> Fix: NullPointerException in case of not existing VNFD ID

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VimManagement.java, core/core-impl/src/test/java/org/openbaton/nfvo/core/test/VimManagementClassSuiteTest.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/VimManagement.java
Refresh/Request images, networks and flavors of VIMs in parallel.
this fixes issue https://github.com/openbaton/NFVO/issues/111
=> Fix: issue-#111

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/PluginManager.java
1) Fixed the name convention for the plugins downloaded from the marketplace.
2) Plugins from the marketplace are still downloaded in the "install-plugin" folder and if no active plugin of the requested type is found a new jar is downloaded.
=> Issue #122

api/src/main/java/org/openbaton/nfvo/api/catalogue/RestVirtualNetworkFunctionDescriptor.java
Added single api function to be able to get a vdu by the vnfd id and the vdu id.
=> Added api for getting vdu directly from vnfd

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/PluginManager.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/NSDUtils.java
Update image name check during onboarding
=> Onboarding checks

api/src/main/java/org/openbaton/nfvo/api/runtime/RestNetworkServiceRecord.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/test/java/org/openbaton/nfvo/core/test/NetworkServiceRecordManagementClassSuiteTest.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/NetworkServiceRecordManagement.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/VnfmManager.java, vnfm/vnfm-int/src/main/java/org/openbaton/vnfm/interfaces/manager/VnfmManager.java
add monitoring ip to nsr create body
=> Monitoring Ip

api/src/main/java/org/openbaton/nfvo/api/runtime/RestNetworkServiceRecord.java
Resume NSR and Start NSR, both had the same path, which meant if no body was sent when creating a NSR the request went to resume and created the issue https://github.com/openbaton/NFVO/issues/144 
After it is merged the swagger-ui can be also updated to reflect the changes.
=> Resume NSR and Start NSR shared similar paths - issue-144

api/src/main/java/org/openbaton/nfvo/api/catalogue/RestVirtualNetworkFunctionDescriptor.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/PluginManager.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VirtualNetworkFunctionManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/VirtualNetworkFunctionManagement.java
Integrity checks were not realized while adding a single VNFD on the catalog.
Please check that it does not break in case of existing databases...in addition, I've heard some issues while using hsqldb
=> Fix for bug #159

api/src/main/java/org/openbaton/nfvo/api/runtime/RestLogs.java, api/src/main/java/org/openbaton/nfvo/api/runtime/RestNetworkServiceRecord.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/core/VNFLifecycleOperationGranting.java, core/core-impl/src/test/java/org/openbaton/nfvo/core/test/NetworkServiceRecordManagementClassSuiteTest.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/NetworkServiceRecordManagement.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/VNFLifecycleOperationGranting.java, openbaton-libs/catalogue/src/main/java/org/openbaton/catalogue/nfvo/messages/VnfmOrScalingMessage.java, repository/src/main/java/org/openbaton/nfvo/repositories/VimRepository.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/VnfmManager.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/ScalingTask.java, vnfm/vnfm-int/src/main/java/org/openbaton/vnfm/interfaces/manager/VnfmManager.java
This pull request fixes issue #141 
BUT... i did change the rest API, so sdk must be updated as well
=> Fix Issue #141

build.gradle, gradle/gradle/packaging.nfvo.docker.gradle
This gradle task builds a minimal docker container; configuration is done on deploytime via environment variables
=> Imp: initial commit for docker-container build task

catalogue/src/main/java/org/openbaton/catalogue/mano/common/AbstractVirtualLink.java, catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/VNFDConnectionPoint.java, catalogue/src/main/java/org/openbaton/catalogue/mano/descriptor/VirtualLinkDescriptor.java, core/core-impl/build.gradle, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/NetworkServiceRecordManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/core/NetworkManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/NSDUtils.java, core/core-impl/src/test/java/org/openbaton/nfvo/core/test/NetworkManagementClassSuiteTest.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/NetworkManagement.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/tasks/HealTask.java
This PR fixes: 
* #126 
* [ openstack4j #25](https://github.com/openbaton/openstack4j-plugin/issues/25)
* [ openstack4j #9](https://github.com/openbaton/openstack4j-plugin/issues/9)
=> fea add support for fix ip and cidr

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VNFPackageManagement.java
=> fix: proper cast of the imageIds

gradle/gradle/packaging.nfvo.debian.gradle, gradle/gradle/scripts/debian/postinst
Add configurations for new service mechanism
=> Indep rabbitmq

api/src/main/java/org/openbaton/nfvo/api/interceptors/InterceptorConfiguration.java, registration/src/main/java/org/openbaton/registration/Registration.java, security/src/main/java/org/openbaton/nfvo/security/components/ComponentManager.java
This fixes partly the issue 32 in the generic-vnfm. The registration module does not try to register multiple times anymore. This logic is moved to the vnfm-sdk.
=> Fix: Registration of managers

etc/openbaton.properties, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/state/MessageGenerator.java
fixes issue #199 
related pull request in generic VNFM: https://github.com/openbaton/generic-vnfm/pull/39
=> imp: make NFVO unaware about EMS

api/src/main/java/org/openbaton/nfvo/api/admin/RestComponents.java, common/src/main/java/org/openbaton/nfvo/common/utils/key/KeyHelper.java, security/src/main/java/org/openbaton/nfvo/security/components/ComponentManager.java
This improves the usability since in the case of an exception, the message is not returned properly to the client sending the HTTP request.
This pull request should be closed together with pull request 15 in the openbaton-client.
=> Imp: Let RestComponents::registerService return JsonObject instead of String

core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VimManagement.java, main/src/main/java/org/openbaton/nfvo/system/FlywayConfig.java
fix error: DROP PROCEDURE IF EXISTS `?`
When launching NFVO with in memory db.
Fix warning message: DB: PROCEDURE openbaton.? does not exist (SQL State: null - Error Code: 1305)
When launching NFVO with mysql
=> fix: fix baseLineVersion and format code

tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VNF/VNFInterfaces.java
Fixed saving of lifecycle events properly
=> Tosca lifecycle fix

common/src/main/java/org/openbaton/nfvo/common/utils/key/KeyHelper.java, security/src/main/java/org/openbaton/nfvo/security/authorization/UserManagement.java
One NullPointerException and one ArrayOutOfBoundsException were not caught before.
=> Fix: Catch exceptions

api/src/main/java/org/openbaton/nfvo/api/runtime/RestNetworkServiceRecord.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/NSDUtils.java
Add Swagger annotation and Javadoc for two APIs:
* switchToRendundantVNFCInstance
* postStandByVNFCInstance
=> Add Swagger annotation and Javadoc for APIs

core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/CheckVNFPackage.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/Utils.java
Fix for https://github.com/openbaton/NFVO/issues/236
=> imp: add message if corrupted Metadata file

common/src/main/java/org/openbaton/nfvo/common/utils/rabbit/RabbitManager.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/PluginManager.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VNFPackageManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/events/senders/RestEventSender.java, main/src/main/java/org/openbaton/nfvo/system/SystemStartup.java, monitoring/src/main/java/org/openbaton/monitoring/interfaces/MonitoringPluginCaller.java, plugin/src/main/java/org/openbaton/plugin/interfaces/Plugin.java, plugin/src/main/java/org/openbaton/plugin/utils/PluginCaller.java, plugin/src/main/java/org/openbaton/plugin/utils/Utils.java, tosca-parser/src/main/java/org/openbaton/tosca/parser/CSARParser.java, vim-drivers/src/main/java/org/openbaton/vim/drivers/VimDriverCaller.java
Different fixes for improving the use of the resources.
=> Improve resources usage

openbaton.sh
If host user is called "openbaton" previous grep does not work
=> Fix: fix the check for openbaton existing screens

tosca-parser/src/main/java/org/openbaton/tosca/parser/TOSCAParser.java
adding QoS policy in the Virtual Link of the VNF descriptor while parsing the csar file of the NSD
=> Adding QoS in the VL of the VNFD while parsing the csar file

api/src/main/java/org/openbaton/nfvo/api/admin/RestVimInstances.java
=> Imp: Add API method for deleting multiple VIMs at once

gradle/gradle/scripts/debian/postinst
=> Fix: fix properties file during upgrade

tosca-parser/src/main/java/org/openbaton/tosca/parser/TOSCAParser.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/CP/CPProperties.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VDU/VDUProperties.java, tosca-parser/src/main/java/org/openbaton/tosca/templates/TopologyTemplate/Nodes/VNF/VNFProperties.java
Added the Metadata option for the TOSCA yaml descriptor for VNFD, VDU, CP.
=> Tosca metadata

api/src/main/java/org/openbaton/nfvo/api/interceptors/SchemaValidatorInterceptor.java, catalogue/src/main/java/org/openbaton/catalogue/nfvo/VNFPackageMetadata.java, common/src/main/java/org/openbaton/nfvo/common/utils/schema/SchemaValidator.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/api/VNFPackageManagement.java, core/core-impl/src/main/java/org/openbaton/nfvo/core/utils/CheckVNFPackage.java, core/core-int/src/main/java/org/openbaton/nfvo/core/interfaces/VNFPackageManagement.java, main/src/main/java/org/openbaton/nfvo/system/RabbitConfiguration.java, main/src/main/resources/application.properties, tosca-parser/src/main/java/org/openbaton/tosca/parser/CSARParser.java, vnfm/vnfm-impl/src/main/java/org/openbaton/nfvo/vnfm_reg/VnfmManager.java
Mainly removing the check while uploading vnf package and fix csar parsing consequently.
=> Vnfpacmgmt
